baseURL = "https://aclaudiap.github.io/meu-portifolio-doc/"
languageCode = "pt-br"
title = "Portfólio | Claudia"
theme = "FixIt"

[params]
  defaultTheme = "light"

  [params.home]
    [params.home.profile]
      enable = true
      title = "Olá, eu sou a Claudia"
      subtitle = "Documentação Técnica | Processos | Tecnologia"
      social = true

    # Esta seção abaixo garante que os posts não apareçam na tela principal
    [params.home.posts]
      enable = false

  [params.social]
    GitHub = "aclaudiap"
    Linkedin = "aclaudiap"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Documentação"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "curriculo"
    name = "Currículo"
    url = "/curriculo/"
    weight = 2