baseURL = "https://aclaudiap.github.io/portifolio-tw/"
languageCode = "pt-br"
title = "Welcome!"
theme = "FixIt"

[params]
  defaultTheme = "light"

  # 1. Configuração do Autor (Para sumir o Anonymous)
  [params.author]
    name = "Ana Claudia"
    link = "https://github.com/aclaudiap"

  [params.section]
    enableCount = false
  
  [params.page]
    # 2. Desativação total de Metadados (Para sumir a data e o ícone de bonequinho)
    author = false        # Remove o nome/ícone de autor abaixo do título
    date = false          # Remove a data
    enableDate = false
    enablePublishDate = false
    enableLastMod = false
    wordCount = false
    readingTime = false
    editSource = false    # Remove link de editar página
    backToTop = true

  [params.home]
    [params.home.profile]
      enable = true
      title = "Ana Claudia"
      subtitle = "Technical Writing • Doc-as-Code • Technology"
      social = true
      avatarURL = "" 

    [params.home.posts]
      enable = false

  [params.social]
    GitHub = "aclaudiap"
    Linkedin = "aclaudiap"

[menu]
  # Menu Principal
  [[menu.main]]
    identifier = "posts"
    name = "Case: Doc-as-Code"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "curriculo"
    name = "Resume"
    url = "/curriculo/"
    weight = 2

  # Submenus
  [[menu.main]]
    parent = "posts"
    name = "Setup & Tools"
    url = "/posts/1-ferramentas-e-acessos"
    weight = 1

  [[menu.main]]
    parent = "posts"
    name = "Deployment Guide"
    url = "/posts/2-passo-a-passo"
    weight = 2

  [[menu.main]]
    parent = "posts"
    name = "Troubleshooting"
    url = "/posts/3-erros-e-solucoes"
    weight = 3

  [[menu.main]]
    parent = "posts"
    name = "Release Notes"
    url = "/posts/4-historico-de-versoes"
    weight = 4